services:
  backend:
    command: go run main.go
    volumes:
      - ./backend:/app
    environment:
      - GIN_MODE=debug

  frontend:
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
