services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - PORT=8080
    networks:
      - dorkgen-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    networks:
      - dorkgen-network
    restart: unless-stopped

networks:
  dorkgen-network:
    driver: bridge
